[build]
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"
[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
